CREATE TABLE IF NOT EXISTS DF_SAAS_APP
(
   APP_ID             BIGINT NOT NULL AUTO_INCREMENT,
   PROVIDER           VARCHAR(120) NOT NULL,
   URL                VARCHAR(255) NOT NULL,
   NAME               VARCHAR(255) NOT NULL,
   VERSION            VARCHAR(64) NOT NULL,
   CATEGORY           VARCHAR(64),
   DESCRIPTION        TEXT,
   ICON_URL           VARCHAR(255) NOT NULL,
   CREATE_TIME        DATETIME,
   HOTNESS            INT NOT NULL,
   PRIMARY KEY (APP_ID)
)  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_SAAS_APP_INSTANCE
(
   INSTANCE_ID        BIGINT NOT NULL AUTO_INCREMENT,
   APP_ID             BIGINT NOT NULL,
   APP_VERSION        VARCHAR(64) NOT NULL,
   PROJECT            VARCHAR(120) NOT NULL,
   NAME               VARCHAR(255) NOT NULL,
   USER               VARCHAR(120) NOT NULL,
   CREATE_TIME        DATETIME,
   PRIMARY KEY (INSTANCE_ID)
)  DEFAULT CHARSET=UTF8;