CREATE TABLE IF NOT EXISTS DF_SAAS_APP_2
(
   APP_ID             VARCHAR(64) NOT NULL,
   PROVIDER           VARCHAR(120) NOT NULL,
   URL                VARCHAR(255) NOT NULL,
   NAME               VARCHAR(255) NOT NULL,
   VERSION            VARCHAR(64) NOT NULL,
   CATEGORY           VARCHAR(64),
   DESCRIPTION        TEXT,
   ICON_URL           VARCHAR(255) NOT NULL,
   CREATE_TIME        DATETIME,
   HOTNESS            INT NOT NULL,
   PRIMARY KEY (APP_ID)
)  DEFAULT CHARSET=UTF8;

